/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import COD_main.Customer;
import database_conn.DbConnect;
import java.util.ArrayList;

/**
 *
 * @author Petru Botnar;
 */
//account panel class that displays the details of the customer account
public class AccountPanel extends javax.swing.JPanel {

    private Customer customer;
    private DbConnect db = new DbConnect();
    private ArrayList<String> cust_det;

    //account panel constructor
    public AccountPanel(Customer c, boolean b) {
        this.customer = c;
        //get details of the current customer
        cust_det = db.GetCustomerDetails(customer.getUser_id());
        initComponents();
        //displaying customer name and surname
        nameL.setText(cust_det.get(0) + " " + cust_det.get(1));
        //displaying customer spending balance
        sL.setText("£ " + cust_det.get(2));
        //displaying customer phone number
        phone.setText(cust_det.get(3));
        //displaying customer vip club status
        club.setText(cust_det.get(4));

        //vip extra information
        //if customer is vip the specific data will be displayed
        jLabel2.setVisible(b);
        club.setVisible(b);

    }
    //method to update the customer details
    public void UpdateDetails() {
        cust_det = db.GetCustomerDetails(customer.getUser_id());
        nameL.setText(cust_det.get(0) + " " + cust_det.get(1));
        sL.setText("£ " + cust_det.get(2));
        phone.setText(cust_det.get(3));
        club.setText(cust_det.get(4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        spending = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        sL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        club = new javax.swing.JLabel();

        name.setText("Full name:");

        spending.setText("Total Spending:");

        nameL.setText("name");

        sL.setText("balance");

        jLabel1.setText("Phone number:");

        phone.setText("phone");

        jLabel2.setText("VIP Club:");

        club.setText("club");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(spending, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nameL))
                    .addComponent(club)
                    .addComponent(sL)
                    .addComponent(phone))
                .addGap(0, 243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spending)
                    .addComponent(sL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(club))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel club;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameL;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel sL;
    private javax.swing.JLabel spending;
    // End of variables declaration//GEN-END:variables
}
