/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import COD_main.Item;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JLabel;

/**
 *
 * @author Petru Botnar;
 */
//item panel class definition
//this class is used as a template to display menu items on the menu
//including buttons to increment and decrement quantity
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     */
    String id;
    int quant = 0;
    Item item;
    DecimalFormat df = new DecimalFormat("#.00");
    
    //item panel constructor that takes an item object as argument
    public ItemPanel(Item item) {
        initComponents();
        this.item = item;
        //displaying item title
        itemName.setText(item.getTitle());
        //displaying item price
        itemPrice.setText("£ " + df.format(item.getPrice()));
        //displaying selected quantity
        quantity.setText(Integer.toString(quant));
        //storing item id reference
        id = item.getItem_id();
        setVisible(true);
    }

    public ItemPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemName = new javax.swing.JLabel();
        itemPrice = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        quantity = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        itemName.setText("itemName");

        itemPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        itemPrice.setText("price");

        addButton.setText("+");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        quantity.setText("0");

        removeButton.setText("-");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(itemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(quantity)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(itemName)
                .addComponent(itemPrice)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //when add button is pressed the quantity increments by 1
        quant++;
        //new quantity is displayed
        quantity.setText(Integer.toString(quant));
        //ordered quantity is set in the item object
        item.setOrdered_quantity(quant);
        //change color background for selected items
        setBackground(Color.yellow);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       //when remove button is pressed the quantity decrements by 1 if is not negative
        if (quant > 0) {
            quant--;
            //new quantity is displayed
            quantity.setText(Integer.toString(quant));
            //ordered quantity is set in the item object
            item.setOrdered_quantity(quant);
        }
        if (quant <= 0) {
            //change color background to default if items are not selected(ie quantity is zero)
            setBackground(new Color(240, 240, 240));
        }
        repaint();
    }//GEN-LAST:event_removeButtonActionPerformed
    //method to set the order componets visibility (buttons and quantity)
    public void SetOrderButtonsVisibility(boolean b) {
        addButton.setVisible(b);
        removeButton.setVisible(b);
        quantity.setVisible(b);
    }
    //method to reset the item panel to its default
    public void reset(){
        setBackground(new Color(240, 240, 240));
        quant = 0;
        quantity.setText("0");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel itemPrice;
    private javax.swing.JLabel quantity;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
