/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import COD_main.Customer;
import COD_main.User;
import database_conn.DbConnect;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.util.DigestUtils;

/**
 *
 * @author Petru Botnar;
 */
//login panel class definition
//this class is used to login into the system
public class LoginPanel extends javax.swing.JPanel {

    User user;
    Customer customer;
    MainFrame mf;
    DbConnect db1;
    boolean vip = false;

    //login panel constructor, initialising main frame and database
    public LoginPanel(MainFrame main) {
        this.mf = main;
        db1 = mf.db;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        try {
            //intilising a customer with the found matching data from the database
            customer = db1.SearchCustomer(nameField.getText(), passField.getText());
            //if a customer with given username and password is found
            if (customer.getUsername() != null) {
                //check if the customer is vip
                if (!customer.getVip_status().equals("null")) {
                    vip = true;
                }
                //initialise a new customer dashboard with the customer, the current main frame and vip status
                CustomerDashboard cd = new CustomerDashboard(customer, mf, vip);
                mf.setCustomerDash(cd);
                //resetting fields to default
                nameField.setText("");
                passField.setText("");
                vip = false;
                //adding customer dashboard to frame
                mf.add(cd);
                //removing extra panels from dashboard
                mf.clearDash();
            } else {
                //if a customer has not been found in the database,
                //a search is run to check if there is a matching staff user
                user = db1.SearchUser(nameField.getText(), passField.getText());
                //if user is found
                if (user.getUsername() != null) {
                    //if the user type is staff
                    if (user.getType().equals("staff")) {
                        //new staffboard is initilised
                        StaffDashboard sd = new StaffDashboard(user, mf);
                        //resetting fields
                        nameField.setText("");
                        passField.setText("");
                        mf.add(sd);
                        mf.clearDash();
                        
                        //if user has type manager
                    } else if (user.getType().equals("manager")) {
                        //manager dashboard is initilised
                        ManagerDashboard md = new ManagerDashboard(user, mf);
                        //resetting fields
                        nameField.setText("");
                        passField.setText("");
                        mf.add(md);
                        mf.clearDash();
                        //if user has type owner
                    } else if (user.getType().equals("owner")) {
                        //manager dashboard is initilised
                        ManagerDashboard md = new ManagerDashboard(user, mf);
                        //resetting fields
                        nameField.setText("");
                        passField.setText("");
                        mf.add(md);
                        mf.clearDash();
                    }
                }
            }
        } catch (Exception e) {
            //if an exception occurs, it means that no customer/user was found, hence wrong username/password message is displayed
            JOptionPane.showMessageDialog(null, "Wrong username/password");
            nameField.setText("");
            passField.setText("");
            System.out.println(e);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    public void setUser(User user) {
        this.user = user;
    }
    //method to reset the customer and user objects to null
    public void reset() {
        user = null;
        customer = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables

}
