/*
 * class that builds an individual order panel for the staff
 */
package GUI;

import COD_main.Item;
import COD_main.Order;
import database_conn.DbConnect;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Vic
 */
public class OrderPanel extends javax.swing.JPanel {
    
    //declarations of the class
    Order order;
    StaffOrdersPanel sop;
    DbConnect db = new DbConnect();
    DecimalFormat df = new DecimalFormat("#.00");
    
    OrderPanel() {
      initComponents();
      setVisible(true);
    }

    
    /**
     * Creates new form OrderPanel, that constructs the panel
     */
    public OrderPanel(Order o, StaffOrdersPanel sop) {
        
        //declarations and initializations
        initComponents();
        this.sop = sop;
        this.order = o;
       
        this.setLayout(new FlowLayout());

        jLabel4.setText(order.getStatus());

        setPreferredSize(new Dimension(650, 90));
        
        //creates a root for a table to display order info
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Order date: " + order.getTime() + " Total: £ " + (df.format(order.getTotal_price())));

        //forloop to get the items from the order
        for(Item i : db.getStaffOrderItems(order))
            {
                //node which attatches onto the root to display the item info of the order
                DefaultMutableTreeNode node = new DefaultMutableTreeNode("x"+i.getOrdered_quantity()+" "+i.getTitle());
                root.add(node);
                //JLabel items = new JLabel("x"+i.getOrdered_quantity()+" "+i.getTitle());   
            }  
            // tree to display our root which contains order info and a node with item info
            JTree tree = new JTree(root);
            add(tree);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jButton1.setText("Take Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ready!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //button which triggers the status of the jlabel to display order status
        String processing = "Processing";
        //updates the order status in the controller class
        order.setStatus(processing);
        jLabel4.setText(processing);
        //inserts the order status and user id who handles the order into the database
        db.InsertOrderStatus(order,sop.user.getUser_id());
        jButton1.setEnabled(false);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //works the same as the button above
        String ready = "Completed";
        order.setStatus(ready);
        jLabel4.setText(ready);
        db.InsertOrderStatus(order,sop.user.getUser_id());
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
