/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import COD_main.Customer;
import COD_main.Item;
import COD_main.Order;
import database_conn.DbConnect;
import java.awt.BorderLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Petru Botnar;
 */
//payment checkout panel definition
//this class is used to display the total amount to be paid
//and contains a payment form for the credit card details to be entered
public class PaymentCheckoutPanel extends javax.swing.JPanel {

    MainFrame mf;
    DbConnect db = new DbConnect();
    DecimalFormat df = new DecimalFormat("#.00");
    ArrayList<Object> discountDetails;
    Customer customer;
    ArrayList<Order> orders;
    double tot_amount = 0;
    double discount = 0;

    //panel form constructor
    //with a list of orders made by a customer
    public PaymentCheckoutPanel(MainFrame mf, ArrayList<Order> o, Customer c) {
        this.mf = mf;
        this.orders = o;
        this.customer = c;
        initComponents();
        PopulateYears();
        discountLabel.setVisible(false);

        //check if the customer has a vip status
        if (customer.getVip_status() != null) {
            //get discount details
            discountDetails = db.GetDiscount();
            //check if discount is active
            if (discountDetails.get(2).toString().equals("true")) {
                //calculate discount
                double tmp = Double.parseDouble(discountDetails.get(0).toString());
                if (tmp != 0) {
                    if (discountDetails.get(1).toString().equals("flexible")) {
                        discount = customer.getSpending() * (tmp / 100);
                    } else {
                        discount = tmp;
                    }
                }
                //display the discount
                String discountString = df.format(discount);
                discountLabel.setVisible(true);
                discountLabel.setText("-" + discountString + "% Discount");
                //add discount to orders
                for (Order or : orders) {
                    or.addDiscount(discount);
                }
            }
        }
        //check if orders have high priority and show the label accordingly
        for (Order or : orders) {
            if (or.isPriority()) {
                priorityLabel.setVisible(true);
            } else {
                priorityLabel.setVisible(false);
            }
            tot_amount += or.getTotal_price();
        }
        //display total amount
        totLabel.setText("£ " + df.format(tot_amount));
    }

    //reset the payment form to default
    public void reset() {
        address.setText("");
        cardNumber.setText("");
        cvv.setText("");
        exp_m.setSelectedIndex(1);
        exp_y.setSelectedIndex(1);
        cardNumber.setText("");
    }

    //method to populate the JComboBox for the expiring year field
    public void PopulateYears() {
        for (int i = 0; i <= 30; i++) {
            exp_y.addItem(15 + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totLabel = new javax.swing.JLabel();
        exp_m = new javax.swing.JComboBox();
        exp_y = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JFormattedTextField();
        cvv = new javax.swing.JFormattedTextField();
        nameOnCard = new javax.swing.JTextField();
        priorityLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();

        jLabel1.setText("Name on card:");

        jLabel2.setText("Card number:");

        jLabel3.setText("Exp date:");

        jLabel4.setText("Cvv:");

        jLabel5.setText("Address:");

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Total Amount:");
        jLabel6.setToolTipText("");

        totLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        exp_m.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        exp_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_mActionPerformed(evt);
            }
        });

        jLabel8.setText("/");

        try {
            cardNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cvv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvActionPerformed(evt);
            }
        });

        priorityLabel.setText("+5% High Priority");

        discountLabel.setText("- Discount %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(address)
                                .addGap(88, 88, 88)
                                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(exp_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(exp_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameOnCard))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(totLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(discountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(priorityLabel)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLabel)
                    .addComponent(discountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(exp_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exp_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(payButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        //pay button action listener
        //checks if all fields are not empty
        //(fields are formatted to accept specific data format)
        if ((!address.getText().isEmpty()) && (!nameOnCard.getText().isEmpty()) && cvv.getValue() != null
                && cardNumber.getValue() != null) {
            mf.remove(this.getParent());
            //orders are added to the database
            for (Order o : orders) {
                db.InsertOrder(o);
            }
            //payment details are stored into the database
            String exp = exp_m.getSelectedItem().toString() + "/" + exp_y.getSelectedItem().toString();
            db.InsertPayment(nameOnCard.getText(), cardNumber.getText(), cvv.getText(), exp, address.getText());
            //customer spending is updated
            customer.addSpending(tot_amount);

            //confirmation message is displayed to the customer
            JOptionPane.showMessageDialog(null, "Payment Successful!");
            //menu panel is reset and added to frame
            mf.cd.menu.reset();
            mf.add(mf.cd.menu, BorderLayout.SOUTH);
            mf.pack();
            reset();
        } else {
            //if empty fields are present a message is displayed
            JOptionPane.showMessageDialog(null, "Please fill in all fields!");
        }

    }//GEN-LAST:event_payButtonActionPerformed

    private void exp_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_mActionPerformed

    private void cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JFormattedTextField cardNumber;
    private javax.swing.JFormattedTextField cvv;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JComboBox exp_m;
    private javax.swing.JComboBox exp_y;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameOnCard;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JLabel totLabel;
    // End of variables declaration//GEN-END:variables
}
