/*
 *This class displays the staff components such as stocks/menu/orders and allows the
    staff to handle pending orders.
 */

package GUI;


import COD_main.User;
import database_conn.DbConnect;
import java.awt.Dimension;
import java.awt.List;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Vic;
 */
public class StaffDashboard extends javax.swing.JPanel {
    //initializations and declarations of the class
    User user;
    MainFrame mf;
    StaffOrdersPanel orders;
    viewStock_Staff vs;
    MenuPanel mp;
    
    boolean activeOrders = true;
    boolean activeStocks = false;
    boolean activeMenu = false;
    boolean activeReport = false;
    
    //class constructor which takes a user and mainframe variable and 
    //delcares them in the class
    public StaffDashboard(User u, MainFrame mf)  {
        this.mf = mf;
        this.user = u;

        
        initComponents();
        helloLabel.setText("Hello "+u.getUsername()+" !!! "+"("+user.getType()+")");
        //initializes order, stock and menu panels 
        orders = new StaffOrdersPanel(u);
        vs = new viewStock_Staff();
        try {
            mp = new MenuPanel(mf, false,null);
        } catch (SQLException ex) {
            Logger.getLogger(StaffDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        backButton.setVisible(false);
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.X_AXIS));
        jPanel1.add(orders);
        add(jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        viewMenuButton = new javax.swing.JButton();
        viewStockButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        helloLabel.setText("Hello Staff!");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        viewMenuButton.setText("View Menu");
        viewMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMenuButtonActionPerformed(evt);
            }
        });

        viewStockButton.setText("View Stock");
        viewStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStockButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewMenuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewStockButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helloLabel)
                    .addComponent(logoutButton)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewMenuButton)
                    .addComponent(viewStockButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mf.remove(this);
        mf.homeDash();
    }//GEN-LAST:event_logoutButtonActionPerformed
 
    /*
    The following code is functionality for the buttons, it works on a basis
    where it checks which panel is active and it uses the series of if statements 
    to remove the panel that needs removing before putting on a new panel that is
    requestes when one of the following buttons is pressed.
    
    */
    private void viewMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMenuButtonActionPerformed
          
       
        if(orders.isShowing())
        {
            jPanel1.remove(orders);
        }
        
        if(vs.isShowing())
        {
            jPanel1.remove(vs);
        }
        

        
      //  jPanel1.remove(orders);
        jPanel1.add(mp);
        mp.SetCheckoutVisible(false);
        mp.setPreferredSize(new Dimension(700,300));    
        backButton.setVisible(true);
        activeMenu = true;
        activeOrders = false;
        jPanel1.repaint();
        jPanel1.revalidate();
        mf.pack();
        
        
        
    }//GEN-LAST:event_viewMenuButtonActionPerformed

    private void viewStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStockButtonActionPerformed
        
        if(orders.isShowing())
        {
            jPanel1.remove(orders);
        }
        
        if(mp.isShowing())
        {
            jPanel1.remove(mp);
        }
             
        //jPanel1.remove(orders);
        jPanel1.add(vs);
        backButton.setVisible(true);
        activeStocks = true;
        activeOrders = false;
        jPanel1.repaint();
        jPanel1.revalidate();
        mf.pack();
     
    }//GEN-LAST:event_viewStockButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        if(activeStocks = true)
        {
            jPanel1.remove(vs);
            jPanel1.add(orders);
            activeStocks = false;
            activeOrders = true;
            backButton.setVisible(false);
        }
        
        if(activeMenu = true)
        {
            jPanel1.remove(mp);
            jPanel1.add(orders);
            activeMenu = false;
            activeOrders = true;
            backButton.setVisible(false);
        }
        
        if(activeReport = true)
        {
            jPanel1.add(orders);
            activeReport = false;
            activeOrders = true;
            backButton.setVisible(false);
        }
        jPanel1.repaint();
        jPanel1.revalidate();
        mf.pack();
        
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton viewMenuButton;
    private javax.swing.JButton viewStockButton;
    // End of variables declaration//GEN-END:variables
}
