/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import database_conn.DbConnect;
import java.util.ArrayList;
import javax.swing.JToggleButton;

/**
 *
 * @author Petru Botnar;
 */
//vip and discount panel definition
//this class is used to set vip threshold limits and a discount
public class VipDiscountPanel extends javax.swing.JPanel {

    /**
     * Creates new form VipDiscountPanel
     */
    ManagerDashboard md;
    DbConnect db = new DbConnect();

    ArrayList<Integer> clubs;
    ArrayList<Object> discount;

    public VipDiscountPanel(ManagerDashboard md) {
        this.md = md;
        initComponents();
        buttonGroup1.add(radioFixed);
        buttonGroup1.add(radioFlexible);

        clubs = db.GetVipThreshold();
        discount = db.GetDiscount();

        _silver.setText(Integer.toString(clubs.get(0)));
        _gold.setText(Integer.toString(clubs.get(1)));
        _diamond.setText(Integer.toString(clubs.get(2)));

        percentage.setText(discount.get(0).toString());

        if (discount.get(1).equals("fixed")) {
            radioFixed.setSelected(true);
        } else {
            radioFlexible.setSelected(true);
        }
        if(discount.get(2).toString().equals("true")){
            on_offButton.setSelected(true);
            on_offButton.setText("ON");
       }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _silver = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        _gold = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        _diamond = new javax.swing.JTextField();
        clubSaveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radioFixed = new javax.swing.JRadioButton();
        radioFlexible = new javax.swing.JRadioButton();
        percentage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveDiscount = new javax.swing.JButton();
        on_offButton = new javax.swing.JToggleButton();
        backButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("VIP Club"));

        jLabel1.setText("SILVER >");

        _silver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _silverActionPerformed(evt);
            }
        });

        jLabel2.setText("GOLD >");

        jLabel3.setText("DIAMOND >");

        clubSaveButton.setText("Save");
        clubSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_silver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_gold, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(_diamond, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clubSaveButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_silver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(_gold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(_diamond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(clubSaveButton))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Discount"));

        radioFixed.setText("Fixed");
        radioFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFixedActionPerformed(evt);
            }
        });

        radioFlexible.setText("Flexible");

        percentage.setText("00");
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });

        jLabel4.setText("%");

        saveDiscount.setText("Save");
        saveDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDiscountActionPerformed(evt);
            }
        });

        on_offButton.setText("OFF");
        on_offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                on_offButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioFixed)
                .addGap(18, 18, 18)
                .addComponent(radioFlexible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(on_offButton)
                .addGap(18, 18, 18)
                .addComponent(saveDiscount)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(radioFixed)
                    .addComponent(radioFlexible)
                    .addComponent(saveDiscount)
                    .addComponent(on_offButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFixedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFixedActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        md.removeDiscountPanel();
    }//GEN-LAST:event_backButtonActionPerformed

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentageActionPerformed

    private void clubSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubSaveButtonActionPerformed
        db.SetVipThreshold(Integer.parseInt(_silver.getText()), Integer.parseInt(_gold.getText()), Integer.parseInt(_diamond.getText()));
    }//GEN-LAST:event_clubSaveButtonActionPerformed

    private void saveDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDiscountActionPerformed
        double p = Double.parseDouble(percentage.getText());
        String type;
        if (radioFixed.isSelected()) {
            type = "fixed";
        } else {
            type = "flexible";
        }
        db.SetDiscount(p, type, on_offButton.isSelected());
    }//GEN-LAST:event_saveDiscountActionPerformed

    private void _silverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__silverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__silverActionPerformed

    private void on_offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_on_offButtonActionPerformed
       
       if(on_offButton.isSelected()){
           on_offButton.setText("ON");
       }else{
           on_offButton.setText("OFF");
       }
    }//GEN-LAST:event_on_offButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _diamond;
    private javax.swing.JTextField _gold;
    private javax.swing.JTextField _silver;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clubSaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton on_offButton;
    private javax.swing.JTextField percentage;
    private javax.swing.JRadioButton radioFixed;
    private javax.swing.JRadioButton radioFlexible;
    private javax.swing.JButton saveDiscount;
    // End of variables declaration//GEN-END:variables
}
